### ISSUE TITLE
게시글 Entity의 ID필드 자동생성 오류

### ISSUE THREAD

**Issue by Park-Github** [Park-Github/PTU_TEAM#17]
게시글 엔티티를 persist(영속화)할 때, ID 필드가 GenerationType.IDENTIFY임에도 자동 생성되지 않고 null값이 들어옴.  PK는 null일 수 없다는 에러가 발생. h2 DB의 버전 문제인 것으로 추측중
> GenerationaType.SEQUENCE or GenerationType.AUTO 일때는 자동 생성됨

_Originally posted by ㄹ@Park-Github in https://github.com/Park-Github/PTU_TEAM/issues/5#issuecomment-1788387799_

**Comment by LazoYoung** [comment]
거 제목 좀 짧게 합시다

**Comment by Park-Github** [comment]
수정하겠습니다...
