### ISSUE TITLE
로그인 및 회원가입 서비스

### ISSUE THREAD

**Issue by Park-Github** [Park-Github/PTU_TEAM#2]
## 작업 상세 내용

- [x] 로그인 및 회원가입 뷰 파일 수정
- [x] 로그인 기능 구현
- [x] 로그인 여부에 따라 로그인 및 회원가입 버튼 보이기 & 로그아웃 버튼 숨기기 (Thymeleaf 엔진 사용)
- [x] 로그아웃 기능 구현
- [x] 회원가입 기능 구현

## 참고 사항
- 로그인 API
POST localhost:8080/login 
페이로드 : id, password 

- 회원가입 API
POST localhost8080:/register
페이로드 : id, password, name, nickName, email, contact, birth(추가됨)

- 뷰 파일의 경우 이 이슈 글의 API를 기준으로 뷰 파일을 수정한다(필요시)
> 닉네임은 DB 데이터의 중복 여부를 판단하여 저장한다. (중복 허용 X)

**Comment by Park-Github** [comment]
dev/back-support 브랜치 만듦

**Comment by LazoYoung** [comment]
@Park-Github 이메일도 중복여부 확인할 필요가 있다고 생각합니다.

**Comment by LazoYoung** [comment]
#20 resolved
