### ISSUE TITLE
게시판 - 게시글 UDATE 및 DELETE 구현

### ISSUE THREAD

**Issue by Park-Github** [Park-Github/PTU_TEAM#5]
## 작업 상세 내용

- [x] 뷰 파일 템플릿 엔진 적용
- [x] 게시글 수정 내용 입력받아 DB에 UPDATE
- [x] 게시글 삭제 내용  DELETE
- [x] 게시판 갱신

## 참고 사항
>

**Comment by Park-Github** [comment]
게시글 등록시 Article ID 필드가 GenerationType.IDENTIFY 일때 오류 발생. GenerationType.AUTO, GenerationType.SEQUENCE 일때는 잘 작동. 문제의 원인은 파악하지 못함. h2 DB의 버전 문제인 것으로 추측중

**Comment by LazoYoung** [comment]
잘 해결되지 않는 버그가 있으면 issue를 추가로 만드는 것을 권장합니다
